/**
 * Every reference case, in ladder order.
 *
 * Each case is the smallest wiring that can show what it is there to show,
 * and every entry adds one device or flips one configuration flag against the
 * entry above it. The last three are specialists — they are allowed to be
 * large because what they show cannot be shown in anything smaller.
 *
 * The JSON holds the engine's own results for each snapshot, generated by
 * `tools/export_cases.py`. This barrel lives inside `docs/` on purpose: the
 * case data must be snapshotted with the docs when a version is cut, so an old
 * version keeps showing what its own engine computed. The component that
 * renders it lives in `website/src/` and is shared across versions, so pages
 * pass the data in rather than letting the component reach for it. The
 * property catalog travels the same way and for the same reason.
 */
import GRID_ONLY from './grid-only.json';
import PV_SELF_CONSUMPTION from './pv-self-consumption.json';
import PV_EXPORT from './pv-export.json';
import METERED_LOAD from './metered-load.json';
import CAPTIVE_LOAD from './captive-load.json';
import BATTERY_BASICS from './battery-basics.json';
import CAPTIVE_BATTERY from './captive-battery.json';
import GROUP_CAPTIVITY from './group-captivity.json';
import TWO_PV_SYSTEMS from './two-pv-systems.json';
import MIXED_EXPORT_HOUSE from './mixed-export-house.json';
import CATALOG from '../properties.json';

import type {
  PropertyCatalog,
  ReferenceCase,
} from '@site/src/components/CaseDiagram/types';

export const REFERENCE_CASES = [
  GRID_ONLY,
  PV_SELF_CONSUMPTION,
  PV_EXPORT,
  METERED_LOAD,
  CAPTIVE_LOAD,
  BATTERY_BASICS,
  CAPTIVE_BATTERY,
  GROUP_CAPTIVITY,
  TWO_PV_SYSTEMS,
  MIXED_EXPORT_HOUSE,
] as unknown as ReferenceCase[];

/** What each published property means, its unit, and the layer it belongs to. */
export const PROPERTIES = CATALOG as unknown as PropertyCatalog;

export function referenceCase(id: string): ReferenceCase {
  const found = REFERENCE_CASES.find((c) => c.id === id);
  if (!found) {
    throw new Error(`unknown reference case ${id}`);
  }
  return found;
}

export default REFERENCE_CASES;
